name: pypy_devel API Build
on:
  push:
    branches: ["pypi_devel"]
  pull_request:
    branches: []

jobs:
  python_package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python3
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Build pip package
        run: |
          python -m pip install --verbose .
